### ISSUE TITLE
What IDE I need to use to compile the plugin?

### ISSUE THREAD

**Issue by W0lweR** [OrigamiDream/Avis-WatchDog#1]
What IDE I need to use to compile the plugin? (sorry for bad English)

**Comment by OrigamiDream** [comment]
I used IntelliJ. The source requires spigot 1.8.7 to be compiled.

**Comment by W0lweR** [comment]
> 
> 
> I used IntelliJ. The source requires spigot 1.8.7 to be compiled.

Will it work with **CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)** ?

**Comment by OrigamiDream** [comment]
It's not sure, but if you add the bukkit as a External Library for the source code, you would know whether it works by through unresolved errors.

**Comment by W0lweR** [comment]
Ok, i'll try. But where I can PM you, if i get some problems?

**Comment by OrigamiDream** [comment]
Open an issue.
